BEGIN;

-- USERS
CREATE TABLE IF NOT EXISTS users(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(128) NOT NULL,
    lastName VARCHAR(128) NOT NULL,
    dateBorn TIMESTAMP NOT NULL,
    genderId INTEGER NOT NULL,
    imagen VARCHAR(255) NULL,
    pwd VARCHAR(255) NOT NULL
);

-- USERS GENDERS
CREATE TABLE IF NOT EXISTS usersGender(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gender VARCHAR(64) NOT NULL UNIQUE,
    notes VARCHAR(255) NULL 
);

-- USERS EMAILS
CREATE TABLE IF NOT EXISTS usersEmails(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    categoryId INTEGER NOT NULL,
    userId INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS EmailsCategory(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(64) NOT NULL UNIQUE,
    notes VARCHAR(255) NULL    
);

-- USERS PHONES
CREATE TABLE IF NOT EXISTS usersPhones(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    phone VARCHAR(255) NOT NULL UNIQUE,
    categoryId INTEGER NOT NULL,
    userId INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS phonesCategory(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(64) NOT NULL UNIQUE,
    notes VARCHAR(255) NULL    
);

-- USERS LOCATIONS
CREATE TABLE IF NOT EXISTS usersLocations(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    country VARCHAR(128) NOT NULL,
    provinceState VARCHAR(128) NOT NULL,
    cityTown VARCHAR(128) NOT NULL,
    addressLine VARCHAR(255) NOT NULL,
    userId INTEGER NOT NULL,
    isMain TINYINT NOT NULL DEFAULT 0, 
    notes VARCHAR(255) NULL    
);

-- PRODUCTS
CREATE TABLE IF NOT EXISTS products(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    productName VARCHAR(128) NOT NULL,
    productDescription VARCHAR(255) NOT NULL,
    sku VARCHAR(64) NULL,
    productTerminated VARCHAR(64) NULL,
    categoryId INTEGER NOT NULL,
    priceGross BIGINT NOT NULL,
    priceFinal BIGINT NOT NULL,
    discount INTEGER NOT NULL,
    unitsBuyes INTEGER NULL,
    unitsSelled INTEGER NULL,
    isActive TINYINT NOT NULL DEFAULT 0, 
    notes VARCHAR(255) NULL    
);

-- PRODUCTS CATEGORY
CREATE TABLE IF NOT EXISTS productsCategory(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(64) NOT NULL UNIQUE,
    notes VARCHAR(255) NULL
);

-- PRODUCTS IMAGES
CREATE TABLE IF NOT EXISTS productsImages(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    isMain TINYINT NOT NULL DEFAULT 0,
    imagenDescription VARCHAR(255) NOT NULL,
    pathImagen VARCHAR(255) NOT NULL,
    productId INTEGER NOT NULL
);

-- PRODUCTS TAXES
CREATE TABLE IF NOT EXISTS productsTaxes(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    taxeId INTEGER NOT NULL,
    productId INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS taxes(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    taxeName VARCHAR(64) NOT NULL,
    taxeDescription VARCHAR(255) NOT NULL,
    taxeValue DECIMAL NOT NULL,
    isActive TINYINT NOT NULL DEFAULT 0,
    notes VARCHAR(255) NULL
);

-- CART
CREATE TABLE IF NOT EXISTS cart(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userId INTEGER NOT NULL,
    total BIGINT NOT NULL,
    stateId INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS cartState(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    stateName VARCHAR(64) NOT NULL,
    stateValue TINYINT NOT NULL UNIQUE,
    notes VARCHAR(255) NULL
);

-- TABLE PIVOT USERSCARTS
CREATE TABLE IF NOT EXISTS usersCarts(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userId INTEGER NOT NULL,
    cartId INTEGER NOT NULL
);

-- TABLE PIVOT CARTPRODUCTS(CARTBOX)
CREATE TABLE IF NOT EXISTS cartBox(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    productId INTEGER NOT NULL,
    cartId INTEGER NOT NULL
);

-- ORDERS
CREATE TABLE IF NOT EXISTS orders(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    oderDate DATE NOT NULL,
    cartId INTEGER NOT NULL,
    userLocationId INTEGER NOT NULL,
    guideTransport VARCHAR(128) NULL,
    notes VARCHAR(255) NULL
);

COMMIT;